export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_FAIL = 'FETCH_FAIL'

export const PAYMENT_START = 'PAYMENT_START'
export const PAYMENT_DETAILS_ADDED = 'PAYMENT_DETAILS_ADDED'
export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'

export const GET_LIVE_PRICES = "GET_LIVE_PRICES"

export const GET_BALANCE_START = "GET_BALANCE_START"
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS"
export const GET_BALANCE_FAIL = "GET_BALANCE_START"

// ---BALANCE -----//
export const ETHEREUM_BALANCE = "ETHEREUM_BALANCE"
export const LUMEN_BALANCE = "LUMEN_BALANCE"
export const NAIRA_BALANCE = "NAIRA_BALANCE"
export const RIPPLE_BALANCE = "RIPPLE_BALANCE"
export const BITCOIN_BALANCE = "BITCOIN_BALANCE"
