export const ADMIN_AUTH_START = "ADMIN_AUTH_START";
export const ADMIN_AUTH_SUCCESS = "ADMIN_AUTH_SUCCESS";
export const ADMIN_AUTH_FAIL = "ADMIN_AUTH_FAIL";
export const ADMIN_AUTH_LOGOUT = "ADMIN_AUTH_LOGOUT";

export const MEMBERSHIP_START = "MEMBERSHIP_START";
export const MEMBERSHIP_SUCCESS = "MEMBERSHIP_SUCCESS";
export const MEMBERSHIP_FAIL = "MEMBERSHIP_FAIL";

export const RECIEPIENT_START = "MEEMBERSHIP_START";
export const RECIEPIENT_SUCCESS = "RECIEPIENT_SUCCESS";
export const RECIEPEINT_FAIL = "RECIEPEINT_FAIL";


export const IS_WALLET_ALLOWED = "IS_WALLET_ALLOWED"
export const WALLET_ENABLED = "WALLET_ENABLED"

export const GET_LIVE_PRICES = "GET_LIVE_PRICES"

export const GET_BALANCE_START = "GET_BALANCE_START"
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS"
export const GET_BALANCE_FAIL = "GET_BALANCE_START"

// ---BALANCE -----//
export const ETHEREUM_BALANCE = "ETHEREUM_BALANCE"
export const LUMEN_BALANCE = "LUMEN_BALANCE"
export const NAIRA_BALANCE = "NAIRA_BALANCE"
export const RIPPLE_BALANCE = "RIPPLE_BALANCE"
export const BITCOIN_BALANCE = "BITCOIN_BALANCE"


