export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const MEMBERSHIP_START = "MEMBERSHIP_START";
export const MEMBERSHIP_SUCCESS = "MEMBERSHIP_SUCCESS";
export const MEMBERSHIP_FAIL = "MEMBERSHIP_FAIL";

export const RECIEPIENT_START = "MEEMBERSHIP_START";
export const RECIEPIENT_SUCCESS = "RECIEPIENT_SUCCESS";
export const RECIEPEINT_FAIL = "RECIEPEINT_FAIL";


export const ANOYNYMOUS_PAYMENT_START = "ANOYNYMOUS_PAYMENT_START";
export const ANOYNYMOUS_PAYMENT_SUCCESS = "ANOYNYMOUS_PAYMENT_SUCCESS";
export const ANOYNYMOUS_PAYMENT_FAIL = "ANOYNYMOUS_PAYMENT_FAIL";

export const IS_WALLET_ALLOWED = "IS_WALLET_ALLOWED"
export const WALLET_ENABLED = "WALLET_ENABLED"

export const GET_LIVE_PRICES = "GET_LIVE_PRICES"
export const GET_LIVE_CRYPTO_PRICES_USD = "GET_LIVE_CRYPTO_PRICES_USD"
export const GET_PAYTICA_USD_RATES = "GET_PAYTICA_USD_RATES"
export const GET_BALANCE_START = "GET_BALANCE_START"
export const GET_BALANCE_SUCCESS = "GET_BALANCE_SUCCESS"
export const GET_BALANCE_FAIL = "GET_BALANCE_START"

// ---BALANCE -----//
export const ETHEREUM_BALANCE = "ETHEREUM_BALANCE"
export const LUMEN_BALANCE = "LUMEN_BALANCE"
export const NAIRA_BALANCE = "NAIRA_BALANCE"
export const RIPPLE_BALANCE = "RIPPLE_BALANCE"
export const BITCOIN_BALANCE = "BITCOIN_BALANCE"

export const GET_AIRTIME_PROVIDER = "GET_AIRTIME_PROVIDER"
export const GET_ELECTRICITY_PROVIDER = "GET_ELECTRICITY_PROVIDER"
export const GET_DATA_PROVIDER = "GET_DATA_PROVIDER"
export const GET_CABLE_PROVIDER = "GET_CABLE_PROVIDER"


